default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: acme_development

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: acme_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>